name=MF_Ds1302RtcActivity
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_Ds1302RtcActivity component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_Ds1302RtcActivity
architectures=*
dot_a_linkage=true
depends=MF_Ds1302RtcRepository
includes=mf_activity_Ds1302RtcActivity.h
