name=MF_NmeaGps
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_NmeaGps component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_NmeaGps
architectures=*
dot_a_linkage=true
depends=MF_ISerial,MF_Commons
includes=mf_activity_NmeaGpsActivity.h,mf_repository_NmeaGpsRepository.h
