name=MF_Pzem004tRepository
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_Pzem004tRepository component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_Pzem004tRepository
architectures=*
dot_a_linkage=true
depends=MF_ISerial
includes=mf_repository_Pzem004tRepository.h
