name=MF_Ds1302RtcRepository
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_Ds1302RtcRepository component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_Ds1302RtcRepository
architectures=*
dot_a_linkage=true
includes=mf_repository_Ds1302RtcRepository.h
