name=MF_HardwareSerialAdapter
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_HardwareSerialAdapter component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_HardwareSerialAdapter
architectures=*
dot_a_linkage=true
depends=MF_ISerial
includes=mf_adapter_HardwareSerialAdapter.h
