name=MF_AnalogPortCActivity
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_AnalogPortCActivity component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_AnalogPortCActivity
architectures=*
dot_a_linkage=true
depends=MF_AnalogPortCModel,MF_AvrMicroRepository,MF_AnalogPortBActivity
includes=mf_activity_AnalogPortCActivity.h
