name=MF_SdCardRepository
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_SdCardRepository component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_SdCardRepository
architectures=*
dot_a_linkage=true
depends=SD
includes=mf_repository_SdCardRepository.h
