name=MF_SerialUtils
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_SerialUtils component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_SerialUtils
architectures=*
dot_a_linkage=true
depends=MF_AvrMicroRepository
includes=mf_utility_SerialUtils.h
