name=MF_HCSR04Activity
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_HCSR04Activity component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_HCSR04Activity
architectures=*
dot_a_linkage=true
depends=MF_HCSR04Repository,MF_AvrMicroRepository,MF_DigitalPortActivity
includes=mf_activity_HCSR04.h
