name=MF_IR_ATMEGA_Repository
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_IR_ATMEGA_Repository component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_IR_ATMEGA_Repository
architectures=*
dot_a_linkage=true
depends=IRremote
includes=mf_repository_IR_ATMEGA_Repository.h
