name=MF_AnalogPortBActivity
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_AnalogPortBActivity component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_AnalogPortBActivity
architectures=*
dot_a_linkage=true
depends=MF_AnalogPortBModel,MF_AvrMicroRepository,MF_Commons
includes=mf_activity_AnalogPortBActivity.h
