name=MF_AnalogPortBModel
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_AnalogPortBModel component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_AnalogPortBModel
architectures=*
dot_a_linkage=true
includes=mf_model_AnalogPortB.h
