name=MF_AnalogPortDActivity
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_AnalogPortDActivity component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_AnalogPortDActivity
architectures=*
dot_a_linkage=true
depends=MF_AnalogPortDModel,MF_AvrMicroRepository,MF_AnalogPortBActivity
includes=mf_activity_AnalogPortDActivity.h
