name=MF_MuxActivity
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_MuxActivity component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_MuxActivity
architectures=*
dot_a_linkage=true
depends=MF_AvrMicroRepository,MF_DigitalPortActivity
includes=mf_activity_muxActivity.h
