name=MF_AvrMicroRepository
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_AvrMicroRepository component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_AvrMicroRepository
architectures=*
dot_a_linkage=true
depends=MF_ISerial,MF_Commons
includes=mf_repository_AvrMicroRepository.h
