name=MF_HCSR04Repository
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_HCSR04Repository component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_HCSR04Repository
architectures=*
dot_a_linkage=true
includes=mf_repository_HCSR04Repository.h
