name=MF_St7735DisplayRepository
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_St7735DisplayRepository component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_St7735DisplayRepository
architectures=*
dot_a_linkage=true
depends=SPI
includes=mf_repository_St7735DisplayRepository.h
