name=avr_mocking_framework
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=AVR mocking framework infrastructure components.
paragraph=Repository, activity, adapter, model and commons components for AVR projects.
category=Other
url=https://github.com/MicroControllerTeamProject/avr_mocking_framework
architectures=*
dot_a_linkage=true
