name=MF_DigitalPortActivity
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_DigitalPortActivity component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_DigitalPortActivity
architectures=*
dot_a_linkage=true
depends=MF_DigitalPortModel,MF_AvrMicroRepository
includes=mf_activity_DigitalPortActivity.h
