name=MF_EepromRepository
version=1.0.0
author=MicroControllerTeamProject
maintainer=MicroControllerTeamProject
sentence=MF_EepromRepository component library.
paragraph=Modular AVR mocking framework component.
category=Other
url=https://github.com/MicroControllerTeamProject/MF_EepromRepository
architectures=*
dot_a_linkage=true
includes=mf_repository_EepromRepository.h
